### PR TITLE
Remove legacy CSRF protection for approve page

### LINKED ISSUE #931: Approval fails with CSRF token error
Approving a new application (e.g. simple-web-app) in version 1.2.1 fails with a CSRF token error:
```
DEBUG: org.springframework.security.web.csrf.CsrfFilter - Invalid CSRF token found for http://localhost:8080/openid-connect-server-webapp/authorize]
```

This is caused by `approve.jsp` relying on 'proprietary' CSRF protection, even though the Spring Security filter is active on the `/authorize` endpoint.

### PR DESCRIPTION
**Pull request by praseodym**
Instead, we rely on the Spring Security CSRF protection, like we already do for the login page. Additionally, we remove the authentication check in`isApproved`, because this is already done by Spring Security (and if not, we have bigger problems to worry about).

Resolves #931.

Because this issue impacts core behaviour, I'd think this would be sufficient reason for a release of 1.2.2.

### CODE REVIEW

File: openid-connect-server/src/main/java/org/mitre/openid/connect/request/ConnectRequestParameters.java [hunk 1]
```diff
@@ -18,31 +18,30 @@
...
 	// extensions
-	public String CSRF = "csrf";
-	public String APPROVED_SITE = "approved_site";
+	String APPROVED_SITE = "approved_site";
 
 	// responses
-	public String ERROR = "error";
-	public String LOGIN_REQUIRED = "login_required";
+	String ERROR = "error";
+	String LOGIN_REQUIRED = "login_required";
```
Comment (praseodym) [inline openid-connect-server/src/main/java/org/mitre/openid/connect/request/ConnectRequestParameters.java]: The `public` modifiers here were removed by IntelliJ IDEA. According to the [JLS (§9.4)](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.4),
> Every method declaration in the body of an interface is implicitly public (§6.6). It is permitted, but discouraged as a matter of style, to redundantly specify the public modifier for a method declaration in an interface.

**Comment by jricher** [comment]
Please revert the removal of "public" from the interface definition as this makes it inconsistent with the rest of the project's style. I'm aware of that style suggestion but it is not applied here. 

Thanks.

**Comment by praseodym** [comment]
Done.

**Comment by sdoxsee** [comment]
Was tripped up by this for the last day :P

This fix sounds great. Would it be possible to merge this and re-release @jricher ? I can't get 1.2.1 working without manually doing all this in my overlay project. Thanks @praseodym!

**Comment by sdoxsee** [comment]
actually, I'm not in production with this yet so I can get around with other testing for now by taking away the csrf protection in user-context.xml for now.

**Comment by jricher** [comment]
Thanks! I can possibly do the pull and release next week. I was having trouble with the integration test environment just before the last release which is how it slipped by. Oops.

**Comment by sdoxsee** [comment]
Thanks for being all over this! Overlay updated with 1.2.2. Cheers!
